/*!
 * Generated by Coremail System
 * http://www.coremail.cn
 */
function gCalendar_initCalendar(cal) {
var NBSP = String.fromCharCode(160);
cal.setYearBeforeMonth(!0), cal.setMonthNames([ '\u4e00\u6708', '\u4e8c\u6708', '\u4e09\u6708', '\u56db\u6708', '\u4e94\u6708', '\u516d\u6708', '\u4e03\u6708', '\u516b\u6708', '\u4e5d\u6708', '\u5341\u6708', '\u5341\u4e00\u6708', '\u5341\u4e8c\u6708' ]);
var n3 = [ '\u661f\u671f\u65e5', '\u661f\u671f\u4e00', '\u661f\u671f\u4e8c', '\u661f\u671f\u4e09', '\u661f\u671f\u56db', '\u661f\u671f\u4e94', '\u661f\u671f\u516d' ], n1 = [ '\u65e5', '\u4e00', '\u4e8c', '\u4e09', '\u56db', '\u4e94', '\u516d' ];
cal.setWeekDayNames(n3), cal.setShortWeekDayNames(n3), cal.setTinyWeekDayNames(n1), cal.setWeekNumberHead('\u5468'), cal.setWeekDayHeads(n1), 
cal.setTodayButtonFormat('yyyy\u5e74M\u6708d\u65e5EEE'), cal.setClearButtonText(NBSP + '\u6e05\u9664' + NBSP);
}
